#region Copyright & License Information
/*
 * Copyright 2007-2019 The d2 mod Developers (see AUTHORS)
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

using OpenRA.Traits;

namespace OpenRA.Mods.D2.Traits
{
	public class D2RevealsShroudInfo : D2AffectsShroudInfo
	{
		[Desc("Stance the watching player needs to see the shroud removed.")]
		public readonly Stance ValidStances = Stance.Ally;

		[Desc("Can this actor reveal shroud generated by the GeneratesShroud trait?")]
		public readonly bool RevealGeneratedShroud = true;

		public override object Create(ActorInitializer init) { return new D2RevealsShroud(init.Self, this); }
	}

	public class D2RevealsShroud : D2AffectsShroud
	{
		readonly D2RevealsShroudInfo info;
		readonly Shroud.SourceType type;

		public D2RevealsShroud(Actor self, D2RevealsShroudInfo info)
			: base(self, info)
		{
			this.info = info;
			type = info.RevealGeneratedShroud ? Shroud.SourceType.Visibility
				: Shroud.SourceType.PassiveVisibility;
		}

		protected override void AddCellsToPlayerShroud(Actor self, Player p, PPos[] uv)
		{
			if (!info.ValidStances.HasStance(p.Stances[self.Owner]))
				return;

			p.Shroud.AddSource(this, type, uv);
		}

		protected override void RemoveCellsFromPlayerShroud(Actor self, Player p) { p.Shroud.RemoveSource(this); }
	}
}
